backend:
  name: github
  branch: main
  repo: kzinthant-d3v/jamkzt

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "content/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Name"
        name: "name"
        widget: "select"
        options: ["kaskar", "alpha"]

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Content"
        name: "body"
        widget: "markdown"

  - name: "premium"
    label: "Premium Page"
    folder: "content/premium"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Name"
        name: "name"
        widget: "select"
        options: ["kaskar", "alpha"]

      - label: "Date"
        name: "date"
        widget: "datetime"
